on:
  pull_request:
    branches:
      - develop
name: Confirm title matches conventional commit spec
jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: npm ci
      - name: Check title
        run: echo ${{github.event.pull_request.title}}" | npm run test:commit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
