on:
  pull_request:
    branches:
      - develop
name: Confirm title matches conventional commit spec
jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Check title
        run: |
          echo "github.event_path.pull_request:$GITHUB_HEAD_REF"
          echo "pullrequesttitle:$GITHUB_EVENT_PATH_PULL_REQUEST_TITLE"
          echo "pullrequest:$GITHUB_EVENT_PATH_PULL_REQUEST"
          echo "pulllll:${{github.event_path}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
