on:
  push:
    branches:
      - main
name: Create PR main -> develop
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create PR from main to develop
        run: gh pr create --base develop --head main --title "Release PR 'main' -> 'develop'" --body "Release PR"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create PR from main to develop
        run: gh pr merge -m -d false -b "merging main into develop"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
