on:
  push:
    branches:
      - main
name: Create PR main -> develop
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Checkout new branch off main
        run: \
           git checkout -b finish-release-${{ steps.package-version.outputs.current-version }}
           git commit --allow-empty
           git push -u origin finish-release-${{ steps.package-version.outputs.current-version }}
      - name: Create PR from main to develop
        run: gh pr create --base develop --title "Release PR 'main' -> 'develop'" --body "Release PR"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
